### ISSUE TITLE
Missing file include and invalid type.

### ISSUE THREAD

**Issue by Razaekel** [jcchurch13/Mechaduino-Firmware#17]
Controller.cpp has a '#include <SPI.h>' but that include is not included in Mechaduino_01.ino, which gives an error on compiling.

After adding '#include "SPI.h"' to the .ino, it gives a ''PROGMEM' does not name a type' error in Parameters.h. Additionally, from what I can find out about PROGMEM in the Arduino, it's only supported in the AVR architecture.

**Comment by Razaekel** [comment]
After removing the references to PROGMEM, it  gave another error about a missing "Wire.h". After adding this include to the .ino, it compiled fine.

**Comment by mikeanton** [comment]
I'm pretty sure I had to upgrade to the most recent Arduino IDE (1.6.12), and then it compiled fine.  I had problems like this as well using a slightly older version (1.6.5).

**Comment by Razaekel** [comment]
@mikeanton You are correct, updating to the latest Arduino IDE (1.6.13) allows it to compile. 

@jcchurch13 This IDE version requirement should be mentioned in the README.

Closing this issue, as it's no longer valid.
