### ISSUE TITLE
Calibration Settings

### ISSUE THREAD

**Issue by yngndrw** [jcchurch13/Mechaduino-Firmware#28]
This is a really cool project that I'm very interested in, but one thing that stood out to me was the need for recompilation when changing settings and during calibration.

Now I'm aware that this microcontroller doesn't have any EEPROM storage, but there are some libraries to use the flash memory for this purpose. https://github.com/cmaglie/FlashStorage

By using flash storage for the calibration, it would then be possible to have the calibration routine writes its calibration directly and skip the recompilation step, making Mechaduino much easier to use.

**Comment by osresearch** [comment]
PR #30 adds this functionality
